# Generated by Django 2.2.2 on 2019-06-24 18:52

from django.db import migrations
from django.conf import settings
import os
import csv

def make_initial_data(apps, schema_editor):
    Book = apps.get_model('core', 'Book')
    file_path = os.path.join(settings.BASE_DIR, 'sample_books.csv')

    with open(file_path) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book = Book(title=row['title'],
                        author=row['author'],
                        url=row['url'],
                        description=row['description'])
            book.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book'),
    ]

    operations = [
        migrations.RunPython(make_initial_data),
    ]
