# Generated by Django 2.2.2 on 2019-06-25 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190624_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
