# Generated by Django 2.2.2 on 2019-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['added_at', 'title']},
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
