# Generated by Django 2.2.2 on 2019-06-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_favorited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
