# Generated by Django 2.2.2 on 2019-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_favorite_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-favorited_at']},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='created_at',
            new_name='favorited_at',
        ),
    ]
