# Generated by Django 2.2.2 on 2019-06-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190628_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['added_at', 'title'], 'permissions': (('can_add_edit_delete', 'Add/Edit/Delete Books'),)},
        ),
    ]
