# Generated by Django 2.2.2 on 2019-06-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190629_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image_url', models.URLField(null=True)),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
