# Generated by Django 2.2.2 on 2019-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booksuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksuggestion',
            name='category',
        ),
        migrations.AddField(
            model_name='booksuggestion',
            name='suggested_categories',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
