# Generated by Django 2.2.2 on 2019-06-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_booksuggestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksuggestion',
            name='url',
            field=models.URLField(),
        ),
    ]
