# Generated by Django 2.2.2 on 2019-07-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190630_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksuggestion',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='booksuggestion',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
